# **MÓDULO 26 - Projeto Final do Aprofundamento de Analytics**

Bem-vindos ao Projeto de Dashboard de E-commerce! Este projeto é uma oportunidade para vocês aplicarem habilidades essenciais de análise de dados em um cenário prático e realista. Vocês irão trabalhar com um conjunto de dados de transações de clientes de uma loja virtual, distribuídos em duas tabelas distintas. O objetivo final é construir um dashboard interativo que facilite a visualização e análise das informações relevantes do e-commerce, utilizando ferramentas como Looker Studio ou Power BI.

**Objetivo do Projeto:**

Tratamento de Dados: Realizar a junção (JOIN) de duas tabelas utilizando SQL para consolidar as informações.
Análise de Dados: Exportar os dados resultantes para um arquivo CSV.
Visualização de Dados: Desenvolver um dashboard interativo e informativo para visualização das principais métricas e insights do e-commerce.

**Tabelas Disponibilizadas:**

**Tabela de Transações:** Contém os registros de transações realizadas pelos clientes, incluindo detalhes como ID da transação, valor e outros.


**Tabela de Dados Pessoais:** Contém as informações pessoais dos clientes, como ID do cliente, nome, genero, cidade, etc.

**Chave de Ligação:** As tabelas se relacionam através da coluna ID_CLIENT, que é a chave identificadora dos clientes.

# Etapas do Projeto:

1. Realizar um JOIN SQL nas duas tabelas, unificando as informações através da coluna ID_CLIENT. Você deve justificar a escolha do JOIN (Inner/ Left/ Right ou Full).

2. Exportar os dados consolidados resultantes do JOIN para um arquivo CSV.

3. Utilizar Looker Studio ou Power BI para importar o arquivo CSV.

4. Criar visualizações interativas que apresentem métricas importantes, como total de vendas, número de transações, distribuição geográfica dos clientes, perfil demográfico dos clientes, entre outros.

Abaixo temos a configuração do ambiente SQL:

In [13]:
import sqlite3
import pandas as pd

In [3]:
df_transacoes = pd.read_csv("TB_TRANSACOES_PROJETO_ECOMM.csv", delimiter=';')
df_clientes = pd.read_csv("TB_CLIENTES_PROJETO_ECOMM.csv", delimiter=';')

In [4]:
conn = sqlite3.connect('projeto.db')
# Carregar o DataFrame no banco de dados SQLite - criando tb_transacoes e tb_clientes
df_transacoes.to_sql('tb_transacoes', conn, index=False, if_exists='replace')
df_clientes.to_sql('tb_clientes', conn, index=False, if_exists='replace')

175

In [5]:
# Função para executar consultas SQL e retornar o resultado como um DataFrame
def run_query(query):
    return pd.read_sql_query(query, conn)

In [10]:
conn = sqlite3.connect('projeto.db')
query = """
SELECT
*
FROM tb_transacoes
INNER JOIN tb_clientes
  ON tb_transacoes.ID_CLIENT = tb_clientes.ID_CLIENT


"""
df = pd.read_sql_query(query, conn)
print(df.head())

   id_client     Category   Price   Card Type state_name First_name  \
0         37  Electronics   72,93  mastercard         ND     Cornie
1         38      Jewelry  121,89  mastercard         PA        Rab
2         39         Baby    64,3  mastercard         MA      Codie
3         40     Outdoors    9,48  mastercard         OR      Scott
4          5     Outdoors   61,95  mastercard         MN     Tanney

        Gender          Job_Title  Id_client
0  Genderqueer             Editor         37
1         Male  Assistant Manager         38
2       Female  Financial Analyst         39
3       Female     Civil Engineer         40
4       Female       VP Marketing          5

Justifique a escolha do JOIN:

A utilização o "INNER JOIN" se torna interessante nesse caso pois resulta apenas as transações que têm cliente correspondente em "tb_clientes", sendo o ideal quando o objetivo é analisar metas de venda e perfil dos compradores que efetivamente realizaram compras.

Exportando o arquivo como CSV:

In [12]:
df.to_csv('dados_ecommerce_final.csv', index=False)

**Dicas para o projeto:**
- Se atente que, como o mesmo cliente realiza mais de 1 transação quando você for trazer alguma métrica relacionada a dados do cliente terá que utilizar o distinct para criar essas métricas no dashboard, se não acabará tendo os dados repetidos.

- Análise sua tabela, entenda a dimensão dos dados, no excel, antes de enviar para o Powerbi ou Looker Studio.

- Tente montar preveamente um roteiro de quais métricas e visualizações irá colocar no dashboard, isso tornará seu processo mais rápido.

- Qualquer dificuldade para subir sua base para as ferramentas de visualização envie a base e o erro encontrado para que os tutores possam te ajudar.

In [14]:
#dimensões

print(df.shape)      # linhas, colunas
print(df.columns)    # lista de colunas disponíveis

(296, 9)
Index(['id_client', 'Category', 'Price', 'Card Type', 'state_name',
       'First_name', 'Gender', 'Job_Title', 'Id_client'],
      dtype='object')

In [15]:
# TIPO DE DADO

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 296 entries, 0 to 295
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id_client   296 non-null    int64
 1   Category    296 non-null    object
 2   Price       296 non-null    object
 3   Card Type   296 non-null    object
 4   state_name  296 non-null    object
 5   First_name  296 non-null    object
 6   Gender      296 non-null    object
 7   Job_Title   296 non-null    object
 8   Id_client   296 non-null    int64
dtypes: int64(2), object(7)
memory usage: 20.9+ KB

In [16]:
#VERIFICAR DUPLICATAS

df.duplicated().sum()   # se > 0, pensar em drop_duplicates()

np.int64(0)

In [17]:
#RESUMO

df.describe(include='all')

,id_client,Category,Price,Card Type,state_name,First_name,Gender,Job_Title,Id_client
count,296.000000,296,296,296,296,296,296,296,296.000000
unique,NaN,22,292,1,39,163,8,100,NaN
top,NaN,Beauty,"9,11",mastercard,TX,Cornie,Female,Teacher,NaN
freq,NaN,21,2,296,32,5,135,10,NaN
mean,86.706081,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86.706081
std,48.881504,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.881504
min,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000
25%,43.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,43.000000
50%,85.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85.500000
75%,127.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,127.250000
max,175.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,175.000000

In [18]:
# VALORES AUSENTES

df.isnull().sum()

id_client     0
Category      0
Price         0
Card Type     0
state_name    0
First_name    0
Gender        0
Job_Title     0
Id_client     0
dtype: int64

In [23]:
# CONTAGEM POR CLIENTE

pivot_clientes = pd.DataFrame({
    'metríc­a': ['clientes_unicos'],
    'valor'  : [ df_transacoes['id_client'].nunique() ]
})
print(pivot_clientes)

          metríc­a  valor
0  clientes_unicos    241

In [24]:
conn = sqlite3.connect('projeto.db')
query = """
SELECT
  COUNT(DISTINCT id_client) AS clientes_unicos
FROM tb_transacoes;

"""
df = pd.read_sql_query(query, conn)
print(df.head())

   clientes_unicos
0              241